language: python
dist: xenial
python:
  - "3.7-dev"
install:
  - pip3 install -r requirements.txt
  - pip3 install codecov
  - pip3 install coverage
  - wget $PULL_LINK
script:
  - coverage run -m userbot ttt && coverage report
after_success:
  codecov
notifications:
  webhooks:
    urls:
      - https://fathomless-fjord-24024.herokuapp.com/notify
    on_success: always
    on_failure: always
    on_start: never
